# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db543e1c9fa40b0cbb827876150c2631124dfffd749601b50bfdb8901faa546907f6831d9ce24aa8a89720532d7372170f2ea96ca92742f152872c2f4aac4c13

test:
  secret_key_base: 49f154fa2be53212715f358f7df34507eaad3de9904ba8569dae54889f0138912051b36c99c0ef27056ef625fbcd10617ac621d09b7e37deb8622666fd399fc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
